version: 0.2

phases:
  build:
    commands:
      - echo "Starting build..."
      - echo "No build steps required for static HTML, directly zipping files."
  post_build:
    commands:
      - echo "Build complete. Preparing artifacts for deployment."
      

artifacts:
  files:
    - '**/index.html'            
  base-directory: '.'    
  discard-paths: yes    

  name: website_artifact
